name: prod_POC.DM_PROCEDURE_APPLI_2210_2211
source: snowflake
type: raw_sql
rawSql: |-
  SELECT
          id,
          '[ahamo]手続き変更' AS "event_type",
          DM_PROCEDURE_APPLI_2210_2211.ACCTID AS "user_id",
          EXTRACT(EPOCH from CONVERT_TIMEZONE('Asia/Tokyo', 'UTC', ORDER_REGISTRATION_DAY_TS)) AS "time",
          DM_PROCEDURE_APPLI_2210_2211.SERVICE_NAME AS "Service_Name",
          DM_PROCEDURE_APPLI_2210_2211.DATE AS "Date",
          DM_PROCEDURE_APPLI_2210_2211.USE_CASE_NAME AS "サービス名",
          DM_PROCEDURE_APPLI_2210_2211.USE_CASE_NAME AS "手続き名",
          DM_PROCEDURE_APPLI_2210_2211.ORDER_REGISTRATION_DAY AS "適用日",
          DM_PROCEDURE_APPLI_2210_2211.ORDER_REGISTRATION_DAY AS "手続き変更_申し込み日"
  FROM POC.DM_PROCEDURE_APPLI_2210_2211
  WHERE DM_PROCEDURE_APPLI_2210_2211.ACCTID IS NOT null
isSchema: false
primaryKey: ID
