name: prod_POC.DM_AHAMO_KAKEHODAI_GIVE_ABOLISHED_2210_2211
source: snowflake
type: raw_sql
rawSql: |-
  SELECT
    id,
    '[ahamo]かけ放題契解約' AS "event_type",
    DM_AHAMO_KAKEHODAI_GIVE_ABOLISHED_2210_2211.ACCTID AS "user_id",
    EXTRACT(EPOCH from CONVERT_TIMEZONE('Asia/Tokyo', 'UTC', ORDER_REGISTRATION_DATE_TS)) AS "time",
    DM_AHAMO_KAKEHODAI_GIVE_ABOLISHED_2210_2211.SERVICE_NAME AS "Service_Name",
    DM_AHAMO_KAKEHODAI_GIVE_ABOLISHED_2210_2211.DATE AS "Date",
    DM_AHAMO_KAKEHODAI_GIVE_ABOLISHED_2210_2211.ORDER_REGISTRATION_DATE AS "かけ放題_申し込み日",
    DM_AHAMO_KAKEHODAI_GIVE_ABOLISHED_2210_2211.AHAMO_KAKEHODAI_CONTRACT_DAY AS "かけ放題_適用日",
    DM_AHAMO_KAKEHODAI_GIVE_ABOLISHED_2210_2211.AHAMO_KAKEHODAI_APPLY_CODE AS "かけ放題_契約フラグ"
  FROM POC.DM_AHAMO_KAKEHODAI_GIVE_ABOLISHED_2210_2211
  WHERE DM_AHAMO_KAKEHODAI_GIVE_ABOLISHED_2210_2211.ACCTID IS NOT NULL
isSchema: false
primaryKey: ID
