model: prod-poc-dm-ahamo-kakehodai-give-abolished-2210-2211
destination: ahamo-prod
config:
  type: event
  mappings:
    - to: insert_id
      from: ID
      type: standard
  eventName:
    column: event_type
  userIdFrom: user_id
  configVersion: 0
  timestampFrom: time
  customMappings:
    - to: かけ放題_契約フラグ
      from: かけ放題_契約フラグ
      type: standard
    - to: かけ放題_適用日
      from: かけ放題_適用日
      type: standard
    - to: かけ放題_申し込み日
      from: かけ放題_申し込み日
      type: standard
    - to: Date
      from: Date
      type: standard
    - to: Service_Name
      from: Service_Name
      type: standard
schedule:
  type: manual
schedulePaused: false
